### ISSUE TITLE
Dataset View Order not working

### ISSUE THREAD

**Issue by veshant** [xibosignage/xibo#138]
Hi!
I am trying to sort my dataset, however, it only allows numbers in the field.  I have tried changing the html with the chrome inspector, but when I save, no data is pulled for the columns.

**Comment by veshant** [comment]
The dataset is still returning blank. I found that on line 537 of modules/datasetview.module.php, it returns blank. After adding text to the return, I confirmed that it is hitting that.

**Comment by dasgarner** [comment]
If Line 537 is blank - then it means whatever filter criteria you have is not returning any data from your dataset.

You need to enable debugging (use the report fault page) and let us know what results you get. The most likely issue is a problem with your filter criteria.

**Comment by veshant** [comment]
When I fill out the filter field it displays the data.  But when the order field is filled out with a column any column name, then no data is returned.

**Comment by dasgarner** [comment]
That is because of the linked bug - it will be saving your order criteria as a number instead of text. Can you try upgrading to 1.7.1 and see if the problem persists?

**Comment by veshant** [comment]
Sorry for the late reply.  I have upgraded to 1.7.1 and the issue is still there.

**Comment by veshant** [comment]
When I add DESC to it, the data displays but it doesn't get ordered.  If I leave it blank or add ASC, the data doesn't display at all.

**Comment by dasgarner** [comment]
Can you enable debugging and recreate the issue?

The sort field just gets appended to the end of the query, so provided you have the column names correctly then it should work.

**Comment by veshant** [comment]
Here is the troubleshoot file link:
https://drive.google.com/file/d/0BxtQzgPeCK1YNnFtbkl0RVBWNTQ/view?usp=sharing

I think this is what your looking for:

"2015-03-02 01:09:20","DataSet","DataSetResults","SELECT  `Time`, `Subject`, `Course`, `Lecturer`, `Room`   FROM (    SELECT  `Subject`, `Course`, `Lecturer`, `Room`, `Start`, `End`, CONCAT(DATE_FORMAT(Start,'%h:%i%p'), ' -  ', DATE_FORMAT(End,'%h:%i%p')) AS 'Time' ,           RowNumber      FROM (       SELECT MAX(CASE WHEN DataSetColumnID = 1 THEN `Value` ELSE null END) AS 'Subject', MAX(CASE WHEN DataSetColumnID = 2 THEN `Value` ELSE null END) AS 'Course', MAX(CASE WHEN DataSetColumnID = 3 THEN `Value` ELSE null END) AS 'Lecturer', MAX(CASE WHEN DataSetColumnID = 4 THEN `Value` ELSE null END) AS 'Room', MAX(CASE WHEN DataSetColumnID = 5 THEN `Value` ELSE null END) AS 'Start', MAX(CASE WHEN DataSetColumnID = 6 THEN `Value` ELSE null END) AS 'End',            RowNumber         FROM (          SELECT datasetcolumn.DataSetColumnID, datasetdata.RowNumber, datasetdata.`Value`             FROM datasetdata               INNER JOIN datasetcolumn               ON datasetcolumn.DataSetColumnID = datasetdata.DataSetColumnID             WHERE datasetcolumn.DataSetID = :dataSetId           ) datasetdatainner       GROUP BY RowNumber     ) datasetdata  WHERE Start < (NOW()+INTERVAL 1 HOUR) AND  End > NOW() ) finalselect  ORDER BY RowNumber  array (
  'dataSetId' => '1',
)"

**Comment by veshant** [comment]
I found a error on line 445 of the dataset.data.class.php
I believe this:                       $order .= ' :order,' . $i;
is supposed to be this:        $order .= ' :order' . $i . ',';

**Comment by veshant** [comment]
The order by has this ":order1" instead of the column name.  I think thats the issue, but I'm not sure how to get the column name instead.
ORDER BY :order1

**Comment by dasgarner** [comment]
:order1 is a parameter value that will be substituted when the query is executed.

Line 445 looks like this: `$order .= ' :order' . $i . ',';` which is correct

The SQL you provided from the LOG did not have any order by clause at all - so that means the order by was empty for that log. Can you try against making sure that the order by is filled in?

**Comment by dasgarner** [comment]
Actually the SQL in your log looks like this:

```
SELECT  `Time`, `Subject`, `Course`, `Lecturer`, `Room`   FROM (    SELECT  `Subject`, `Course`, `Lecturer`, `Room`, `Start`, `End`, CONCAT(DATE_FORMAT(Start,'%h:%i%p'), ' -  ', DATE_FORMAT(End,'%h:%i%p')) AS 'Time' ,           RowNumber      FROM (       SELECT MAX(CASE WHEN DataSetColumnID = 1 THEN `Value` ELSE null END) AS 'Subject', MAX(CASE WHEN DataSetColumnID = 2 THEN `Value` ELSE null END) AS 'Course', MAX(CASE WHEN DataSetColumnID = 3 THEN `Value` ELSE null END) AS 'Lecturer', MAX(CASE WHEN DataSetColumnID = 4 THEN `Value` ELSE null END) AS 'Room', MAX(CASE WHEN DataSetColumnID = 5 THEN `Value` ELSE null END) AS 'Start', MAX(CASE WHEN DataSetColumnID = 6 THEN `Value` ELSE null END) AS 'End',            RowNumber         FROM (          SELECT datasetcolumn.DataSetColumnID, datasetdata.RowNumber, datasetdata.`Value`             FROM datasetdata               INNER JOIN datasetcolumn               ON datasetcolumn.DataSetColumnID = datasetdata.DataSetColumnID             WHERE datasetcolumn.DataSetID = :dataSetId           ) datasetdatainner       GROUP BY RowNumber     ) datasetdata  WHERE Start < (NOW()+INTERVAL 1 HOUR) AND  End > NOW() ) finalselect  ORDER BY  :order,1 array (
  'dataSetId' => '1',
  'order1' => 'Room',
)
```

I have just noticed that this bug was fixed: #191, perhaps you can see the contents of that issue?

**Comment by veshant** [comment]
Hi Dan,
The issue still exists, the data is not being ordered.  I have extracted the query from the log page.  Here it is:

SELECT `Time`, `Subject`, `Course`, `Lecturer`, `Room` FROM ( SELECT `Subject`, `Course`, `Lecturer`, `Room`, `Start`, `End`, CONCAT(DATE_FORMAT(Start,'%h:%i%p'), ' - ', DATE_FORMAT(End,'%h:%i%p')) AS 'Time' , RowNumber FROM ( SELECT MAX(CASE WHEN DataSetColumnID = 1 THEN `Value` ELSE null END) AS 'Subject', MAX(CASE WHEN DataSetColumnID = 2 THEN `Value` ELSE null END) AS 'Course', MAX(CASE WHEN DataSetColumnID = 3 THEN `Value` ELSE null END) AS 'Lecturer', MAX(CASE WHEN DataSetColumnID = 4 THEN `Value` ELSE null END) AS 'Room', MAX(CASE WHEN DataSetColumnID = 5 THEN `Value` ELSE null END) AS 'Start', MAX(CASE WHEN DataSetColumnID = 6 THEN `Value` ELSE null END) AS 'End', RowNumber FROM ( SELECT datasetcolumn.DataSetColumnID, datasetdata.RowNumber, datasetdata.`Value` FROM datasetdata INNER JOIN datasetcolumn ON datasetcolumn.DataSetColumnID = datasetdata.DataSetColumnID WHERE datasetcolumn.DataSetID = :dataSetId ) datasetdatainner GROUP BY RowNumber ) datasetdata WHERE Start < (NOW()+INTERVAL 1 HOUR) AND End > NOW() ) finalselect ORDER BY :order1 array (
'dataSetId' => '1',
'order1' => 'Room',
)
![log](https://cloud.githubusercontent.com/assets/10793938/6480860/35f1fe34-c293-11e4-9d85-dda1f59bbece.png)

**Comment by veshant** [comment]
I checked the mysql general log to see the final query, this is the query I am getting:
```
		  140 Query	SELECT  `Time`, `Subject`, `Course`, `Lecturer`, `Room`   FROM (    SELECT  `Subject`, `Course`, `Lecturer`, `Room`, `Start`, `End`, CONCAT(DATE_FORMAT(Start,'%h:%i%p'), ' -  ', DATE_FORMAT(End,'%h:%i%p')) AS 'Time' ,           RowNumber      FROM (       SELECT MAX(CASE WHEN DataSetColumnID = 1 THEN `Value` ELSE null END) AS 'Subject', MAX(CASE WHEN DataSetColumnID = 2 THEN `Value` ELSE null END) AS 'Course', MAX(CASE WHEN DataSetColumnID = 3 THEN `Value` ELSE null END) AS 'Lecturer', MAX(CASE WHEN DataSetColumnID = 4 THEN `Value` ELSE null END) AS 'Room', MAX(CASE WHEN DataSetColumnID = 5 THEN `Value` ELSE null END) AS 'Start', MAX(CASE WHEN DataSetColumnID = 6 THEN `Value` ELSE null END) AS 'End',            RowNumber         FROM (          SELECT datasetcolumn.DataSetColumnID, datasetdata.RowNumber, datasetdata.`Value`             FROM datasetdata               INNER JOIN datasetcolumn               ON datasetcolumn.DataSetColumnID = datasetdata.DataSetColumnID             WHERE datasetcolumn.DataSetID = '1'           ) datasetdatainner       GROUP BY RowNumber     ) datasetdata  WHERE Start < (NOW()+INTERVAL 1 HOUR) AND End > NOW() ) finalselect  ORDER BY  'Room'
```

I don't understand why it is not being ordered.  It seems that the query is correct in mysql.

**Comment by veshant** [comment]
I think the issue is that PDO by default adds quotes to make the variables into strings.  I have checked that when I add quotes to the order by it doesn't work, but without the quotes it does work!

**Comment by dasgarner** [comment]
Very helpful indeed! Please try the attached patch, I hope its fixed!

**Comment by veshant** [comment]
Hi @dasgarner,
Everything seems to be fine now.  Thanks a lot for the help!

**Comment by dasgarner** [comment]
Thank you for your help!! it was most useful.
