### ISSUE TITLE
Widget: RGraph Module

### ISSUE THREAD

**Issue by dasgarner** [xibosignage/xibo#1414]
Graphic module for datasets

**Comment by dasgarner** [comment]
I have had to slip this to 1.8.7 due to time pressure for the 1.8.6 release.

**Comment by dasgarner** [comment]
@LukyLuke - can you clarify the status of canvas vs SVG? It looks like you've decided to go only with canvas support for now?

If that is true, can I remove references to the SVG files so that we reduce the number of files that the Players have to download?

**Comment by LukyLuke** [comment]
Thanks for asking

1) You can remove the SVG files, yes. There ist also an option in the code where the HTML is processed. This was/is a tryout for making the graphs more configurable. but it can be added later or switched.

2) I did copy this from a different module from you and never tried it out (shame on me). So I was thinking tis is something you needed in Xibo for switching from one sline to the other :) If not, just remove it!

3) The option to have multiple Datasets is to correlate Data from different sources. For example:
- DataSet 1: Remote-Dataset from Bugtracker about the amount of new Bugs every day
- DataSet 2: Remote-Dataset from a Quality-Gate (Sonarcube or what ever) to get the amount of Unittested Conditions/Lines or number of tests

I guess normally when you just fill in all Data in one DataSet, all is fine. But as soon as you want to correlate different sources of data, this can be complicated.

Other Example: Correlate the achieved work with the planned one
- Static Dataset: Amount of Story-Points we want to achieve in the current planning horizon (let's say 4 Sprints)
- Remote Dataset: Fetching the number of closed story points every day
- Remote Dataset: Fetching the number of resolved bugs every day

Or less technical:
- Remote Dataset: Live-Statistics about Rain or Sun (hourly)
- Remote Dataset: Live-Statistics about traffic on a street

**Comment by dasgarner** [comment]
I see - interesting approach

I had imagined it would compile a single DataSet, from which you'd select how you wanted to plot that data - for example you would say:

Col1 as X Axis as a Label
Val1 as Y-axis

For each row (perhaps according to a filter and sort) it would then plot the contents of Col1 on the X axis and the contents of Val1 on the Y axis.

If you had another data series, you could have Val2 as Y-axis - or you could designate the contents of a column as a series identifier. 

Something like that anyway.

In my example above I want Plumbs, Cabbage and Feta Cheese (sorry for the examples) along the X axis and then Val1 as the Bar values (on the Y-axis).

If you're pulling from several DataSets at the same time, I am not sure exactly how you can plot that - unless they have exactly the same data points on the x-axis?

**Comment by LukyLuke** [comment]
Ah I see, this is an interresting view. I was thinking always "over time".
You mean soomething like this, if I understand you right:
```
  |
9 |                      +-+
  |                    +-| |
5 |      +-+         +-| | |        +-+
  |      | |-+       | | | |        | |-+
1 |    +-| | |       | | | |        | | |-+
  |    | | | |       | | | |        | | | |
  |    | | | |       | | | |        | | | |
  +--------------------------------------------
        Plums        Cabbage         Cheese
```
More like a "Grouped by Col1", right?
I will try to add this today :o)


With the data about to have multiple datasets, you're right.
There you have to have the same measurement. or at least the same amount of datapoints.
But, what you also could do is something like this (Burn down/Burn up) to show where you want to go and what the values actually are (ove the last, lets say 5 days):
```
  |
  |.........................................
  |
  |
  |                   /
  |                .-/
  |               /
  |      .--.    /
  |     /    \../
  |  .-/
  +-----------------------------------------
```

**Comment by LukyLuke** [comment]
This was a great Idea, thanks @dasgarner :)
here the Pull-Request: https://github.com/xibosignage/xibo-cms/pull/337

**Groups by Rows**
![Grouped by Rows](https://user-images.githubusercontent.com/962675/37202110-e2782df4-2389-11e8-98c1-ebcc5361eea8.png)

**Groups by Columns**
![Grouped by Columns](https://user-images.githubusercontent.com/962675/37202155-0051b3c2-238a-11e8-80db-b0672036ddd1.png)

**Option to switch**
![Setting to Switch](https://user-images.githubusercontent.com/962675/37202207-21426b94-238a-11e8-8970-540597396f4b.png)

**Comment by LukyLuke** [comment]
Here an example from above with two Datasets:
![Burn-Up](https://user-images.githubusercontent.com/962675/37203440-ee0310cc-238d-11e8-9284-a5e7f1c2c442.png)

**Dataset one: Sprint Target:**
![SprintTarget](https://user-images.githubusercontent.com/962675/37203500-232c3332-238e-11e8-908c-13b17f7799b3.png)

**Dataset two: Acieved Story-Points every day:**
![AchievedSP](https://user-images.githubusercontent.com/962675/37203539-44e4bbe8-238e-11e8-8dcd-6ab2159363d5.png)

**Graph-Configuration**
![Configuration](https://user-images.githubusercontent.com/962675/37203582-6c848ae8-238e-11e8-90b7-f86ed162630e.png)

**Comment by dasgarner** [comment]
Excellent thanks - I will merge and pull the PR now so I can have a look with your examples.

**Comment by dasgarner** [comment]
I am sure I am being stupid! But I still don't get it (although my bar chart does work now, although I am not sure why!).

I have this:

**Comment by LukyLuke** [comment]
If you want to make the *Value* visible, just use one Dataset.
This you can see on your Graph by the green line.

So as "Label" use the "The Date" Column and all others will be used for the graph.

**Comment by dasgarner** [comment]
Ah I see - so how does it know that it should use Value? Because it is the only other column? What happens if there is more than one column per DataSet and we only want to plot 1?

I think what you've done is a great foundation and I can certainly see where you're going with it, but I need to spend some more time with it to understand it better. I will start by creating a specification for how I think Graphs need to be configured so that the user can easily and readily understand what is happening and how to do it. I'll include multiple DataSets per graph in that specification and some details for how things like Layout import/export would work (so that the exporter knows there are DataSets involved) and how the cache notifications work.

If you have any questions please do let me know and thank you so much for your work on this (and the remote DataSets) so far!

**Comment by LukyLuke** [comment]
Exactly, it will use all columns for the values except the one you define as the "Label".

This is just the first "shoot", right. Also I did this only on my thougths on how a graph may be used.
If you have some Ideas on how it's better to choose the label column (Load it in a Dropdown maybe) or if it's better to let the user choose which columns to show, I will happily apply these things :)

**Comment by dasgarner** [comment]
Sure, I realise this is a first shoot - and a good one!

I will write up some ideas and send them over for you to look at - thanks again!

**Comment by dasgarner** [comment]
This is what I have at the moment in terms of a specification - the key consideration is whether or not to allow multiple DataSets per Widget. If yes, then we need to push this to 2.0, if no then we can include it in 1.8.

[Graph Module.pdf](https://github.com/xibosignage/xibo/files/1828492/Graph.Module.pdf)

I am happy to give you access to the source of this PDF if you want to comment/edit directly.

Overall the specification is very similar to the way it works already, with some adjustments to make it clearer how to configure it and how those configuration options are set, etc.

**Comment by LukyLuke** [comment]
This sounds not very different to how it works now.
To summarize that I understand you correct: 
 1. User selects the DataSet he wants to visualize
 2. User selects a Column:
 2.1 ... used for the Labels on X/Y
 2.2 ... used for Values

Where I am stuck at the moment:
 - Y: Do you mean, that the values should be used on Y? Or is this the current "swap X/Y" thing I made for change the grouping...
 - Series Identifier.. ?? Is this the values for the Legend?
 - Y contant line: Shall there be just an input field to give a value for this? Or do you more think on someting like: Every value in a Row makes a horizontal line

I am happy to present you a first change on the weekend hopefully.
Tricky for me will be the different parts to notify and clean up things, but I will figure out how this is done :)

----

For the next Version (2.0) I have some additional Ideas which came up here when I was thinking about the data I get from our ticketing system. I have not finally thought about how and what, but there I will need some aggregation functions as well.
For example: Have one DataSet with a daily amount of selled Cheese, Plums and Apples.
Based on this we want to make different Graphs:
- What sells best (Pie-Chart)
- How much do we sell every day (line or Bar-chart)
- ...

**Comment by dasgarner** [comment]
You're right, its very similar but with a little helping hand for the user (I think anyway). I have updated the document with descriptions for the "used as" selections to try and make that clearer. See attached.

[Graph Module (1).pdf](https://github.com/xibosignage/xibo/files/1832708/Graph.Module.1.pdf)

 > Tricky for me will be the different parts to notify and clean up things, but I will figure out how this is done

I am happy to do those bits if you'd prefer - it wouldn't take me long at all to do that (assuming we're talking about a single DataSet rather than multi)

----------
2.0: I thought about that too and couldn't decide whether it would be best managed at the Widget level or by some way to create a "computed DataSet" which is a basically a query on other DataSets - almost like the Remote DataSet feature, but with a DataSet as the source.

**Comment by LukyLuke** [comment]
Ah, the **Series Identifier** is somehow the aggregation I meant in my example. You're right, with this function it should mostly work.
I will start this weekend and look how much I'm able to do :o)
Btw: The **computed DataSet** sounds interesting for future more complex renderings.

**Comment by dasgarner** [comment]
@LukyLuke just to let you know that I've had time today to start looking at your PR again. After discussing with the team here I've made a few changes to the way it is configured and to the library you're using for Chart rendering.

The work you have done provided me with an excellent basis to make these changes and I wanted to thank you once again. I will let you know when the work in progress I have here is ready to try and would greatly welcome your feedback at that point.

Best wishes!

**Comment by dasgarner** [comment]
I've pushed my changes into the branch via this PR https://github.com/xibosignage/xibo-cms/pull/374

If you'd like to look over them then please do so - they will be merged into release18 in due course. Thanks!

**Comment by LukyLuke** [comment]
Hey @dasgarner ,
that's great news! I will check it out this weekend if I will find a minute and look forward to try it our in our office for a first test.
Thanks for your work!

**Comment by LukyLuke** [comment]
Two small changes occured by y fresh installation:
* Chart.min.js is not availabe in modules/vendor - I guess you missed this because `vendor` is in .gitignore :D
* chart.json needs to be changed as well :o)
```
diff --git a/modules/chart.json b/modules/chart.json
index 6bbb27cf..66dd4d1d 100644
--- a/modules/chart.json
+++ b/modules/chart.json
@@ -1,7 +1,7 @@
 {
-  "title": "Data-Visualization with Graphs",
-  "author": "Lukas Zurschmiede",
-  "description": "A module to visualize from DataSets with a Graph.",
-  "name": "graph",
-  "class": "Xibo\\Widget\\Graph"
+  "title": "Data-Visualization with Charts",
+  "author": "Lukas Zurschmiede, Spring Signage Ltd",
+  "description": "A module to visualize data from a Dataset.",
+  "name": "chart",
+  "class": "Xibo\\Widget\\Chart"
 }
```

**Comment by dasgarner** [comment]
Thanks for the quick review!! and very good catches. I'm always missing `vendor` items from commits, I need to make myself a checklist for it!

I've updated that and pushed.

I'm pleased you like the changes, I was a bit worried as they are quite different to your original. If you find anything you can't model with it, let me know and we can work in some modifications.

**Comment by LukyLuke** [comment]
Oh, I am not that strict, don't worry!
If it's up to me, you can also set the author to "xibo signage". I am happy to help with new ideas and POCs 😃 which ould be useful maybe.

I already have one or two changes in mind which we maybe could use here, but first I will show and use the current state of work for our Teamdisplays.

**Comment by dasgarner** [comment]
Attribution in the licence notice at the top of the files you've modified is a good thing in my opinion - unless you particularly want it removed, in which case, of course that is no problem :smile: 

Thanks once again for your help and contributions - we've got a solid module here I think! be interesting to have your feedback when you've had time to test.
