### ISSUE TITLE
Unable to Register due to error

### ISSUE THREAD

**Issue by dasgarner** [xibosignage/xibo#173]
If a default config is created on the server, the player may be unable to register due to a server error. This relates to the loading and serving of the default config for that player type.

**Comment by laercionit** [comment]
I sent an email about this problem for springsignage.

I conducted a test with the changes made to files.
The CMS does not allow registering Displau profile, but do not let more edit access any Display Profile. Appears whenever the CMS does not support the type of display.

**Comment by laercionit** [comment]
![image](https://cloud.githubusercontent.com/assets/325662/6090680/54529908-ae69-11e4-96a9-622bc7459bd8.png)


After apply your changes....

**Comment by dasgarner** [comment]
Great thanks - I've fixed this and it will appear in the next few commits.

**Comment by laercionit** [comment]
Hello Dan,
I think I still have something wrong.
I did the following tests:

R51 + CMS 1.6.4
R51 + CMS 1.7.1

I realized that the App can register and after performing the downloads the error occurs. Also sent by email to springsignage support.

Another point that I found strange is that not always the APP can connect, have to try a few times to appear successfully registered.

**Comment by laercionit** [comment]
![image](https://cloud.githubusercontent.com/assets/325662/6099732/6d365638-afe7-11e4-82a1-19e73884e8c2.png)

**Comment by dasgarner** [comment]
As this is Android only, lets take it up through our commercial support.
