### ISSUE TITLE
XiboClient has stopped working

### ISSUE THREAD

**Issue by jetski28** [xibosignage/xibo#282]
As per the title I have a few clients where the Xibo Client (1.7.0) stops working with a windows error "XiboClient has stopped working". Issue #51 sounds very much like my issue however looking at the build date between the file provided on Issue #51 and the official release I would assume the bug has been fixed in the latest release.

We have 7 clients which a number are connected wirelessly - the clients where the wireless is a little bit flaky at times causes the Xibo Client to stop working. My other working clients which are running exactly the same schedule/layout, hardware, windows version & xibo client version either have a solid wireless network connection or connected via Ethernet cable.

Below is two event logs when Xibo Client stops working. I have compared these between a couple clients and are basically the same except a couple lines which include the date/time or client name.

One of these clients doesn't have a network connection yet (still in progress) and also crashes like the others after a period of time. Which leads me to think that it doesn't like it when the network connection isn't available.

Log Name:      Application
Source:        Application Error
Date:          18/02/2015 9:57:32 AM
Event ID:      1000
Task Category: (100)
Level:         Error
Keywords:      Classic
User:          N/A
Computer:      NB-SIGNAGE02
Description:
Faulting application name: XiboClient.exe, version: 2.0.0.0, time stamp: 0x54c69567
Faulting module name: KERNELBASE.dll, version: 6.1.7601.18409, time stamp: 0x53159a86
Exception code: 0xe0434352
Fault offset: 0x0000c42d
Faulting process id: 0xbd8
Faulting application start time: 0x01d04871a2ee116c
Faulting application path: C:\Program Files (x86)\Xibo Player\XiboClient.exe
Faulting module path: C:\Windows\syswow64\KERNELBASE.dll
Report Id: 5acbf557-b6f8-11e4-932f-1c75081a6f12
Event Xml:
<Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
  <System>
    <Provider Name="Application Error" />
    <EventID Qualifiers="0">1000</EventID>
    <Level>2</Level>
    <Task>100</Task>
    <Keywords>0x80000000000000</Keywords>
    <TimeCreated SystemTime="2015-02-17T22:57:32.000000000Z" />
    <EventRecordID>1830</EventRecordID>
    <Channel>Application</Channel>
    <Computer>NB-SIGNAGE02</Computer>
    <Security />
  </System>
  <EventData>
    <Data>XiboClient.exe</Data>
    <Data>2.0.0.0</Data>
    <Data>54c69567</Data>
    <Data>KERNELBASE.dll</Data>
    <Data>6.1.7601.18409</Data>
    <Data>53159a86</Data>
    <Data>e0434352</Data>
    <Data>0000c42d</Data>
    <Data>bd8</Data>
    <Data>01d04871a2ee116c</Data>
    <Data>C:\Program Files (x86)\Xibo Player\XiboClient.exe</Data>
    <Data>C:\Windows\syswow64\KERNELBASE.dll</Data>
    <Data>5acbf557-b6f8-11e4-932f-1c75081a6f12</Data>
  </EventData>
</Event>

Log Name:      Application
Source:        .NET Runtime
Date:          18/02/2015 9:57:31 AM
Event ID:      1026
Task Category: None
Level:         Error
Keywords:      Classic
User:          N/A
Computer:      NB-SIGNAGE02
Description:
Application: XiboClient.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.IO.FileNotFoundException
Stack:
   at System.IO.__Error.WinIOError(Int32, System.String)
   at System.IO.FileStream.Init(System.String, System.IO.FileMode, System.IO.FileAccess, Int32, Boolean, System.IO.FileShare, Int32, System.IO.FileOptions, SECURITY_ATTRIBUTES, System.String, Boolean, Boolean)
   at System.IO.FileStream..ctor(System.String, System.IO.FileMode, System.IO.FileAccess, System.IO.FileShare, Int32, System.IO.FileOptions)
   at System.IO.StreamReader..ctor(System.String, System.Text.Encoding, Boolean, Int32)
   at System.IO.StreamReader..ctor(System.String, System.Text.Encoding)
   at System.IO.File.InternalReadAllLines(System.String, System.Text.Encoding)
   at System.IO.File.ReadAllLines(System.String)
   at XiboClient.XiboTraceListener.ProcessQueueToXmds()
   at System.Threading.ThreadHelper.ThreadStart_Context(System.Object)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)
   at System.Threading.ThreadHelper.ThreadStart()

Event Xml:
<Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
  <System>
    <Provider Name=".NET Runtime" />
    <EventID Qualifiers="0">1026</EventID>
    <Level>2</Level>
    <Task>0</Task>
    <Keywords>0x80000000000000</Keywords>
    <TimeCreated SystemTime="2015-02-17T22:57:31.000000000Z" />
    <EventRecordID>1829</EventRecordID>
    <Channel>Application</Channel>
    <Computer>NB-SIGNAGE02</Computer>
    <Security />
  </System>
  <EventData>
    <Data>Application: XiboClient.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.IO.FileNotFoundException
Stack:
   at System.IO.__Error.WinIOError(Int32, System.String)
   at System.IO.FileStream.Init(System.String, System.IO.FileMode, System.IO.FileAccess, Int32, Boolean, System.IO.FileShare, Int32, System.IO.FileOptions, SECURITY_ATTRIBUTES, System.String, Boolean, Boolean)
   at System.IO.FileStream..ctor(System.String, System.IO.FileMode, System.IO.FileAccess, System.IO.FileShare, Int32, System.IO.FileOptions)
   at System.IO.StreamReader..ctor(System.String, System.Text.Encoding, Boolean, Int32)
   at System.IO.StreamReader..ctor(System.String, System.Text.Encoding)
   at System.IO.File.InternalReadAllLines(System.String, System.Text.Encoding)
   at System.IO.File.ReadAllLines(System.String)
   at XiboClient.XiboTraceListener.ProcessQueueToXmds()
   at System.Threading.ThreadHelper.ThreadStart_Context(System.Object)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)
   at System.Threading.ThreadHelper.ThreadStart()
</Data>
  </EventData>
</Event>

**Comment by dasgarner** [comment]
That error should be fixed in my latest personal build: https://github.com/dasgarner/xibo-dotnetclient/blob/master/bin/x86/Release/XiboClient.exe?raw=true

That will make it into 1.7.2 when we release that.

Can you try it?

**Comment by jetski28** [comment]
Cheers! I will give that a go and get back to you.

**Comment by jetski28** [comment]
It seems to be more stable but still crashes with the same error. Event log shows exactly the same thing.

**Comment by dasgarner** [comment]
The important part of your prior log was this line ` at XiboClient.XiboTraceListener.ProcessQueueToXmds() `

Are you sure that is still in there?

**Comment by jetski28** [comment]
Yes it is ...

Application: XiboClient.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.IO.FileNotFoundException
Stack:
   at System.IO.__Error.WinIOError(Int32, System.String)
   at System.IO.FileStream.Init(System.String, System.IO.FileMode, System.IO.FileAccess, Int32, Boolean, System.IO.FileShare, Int32, System.IO.FileOptions, SECURITY_ATTRIBUTES, System.String, Boolean, Boolean)
   at System.IO.FileStream..ctor(System.String, System.IO.FileMode, System.IO.FileAccess, System.IO.FileShare, Int32, System.IO.FileOptions)
   at System.IO.StreamReader..ctor(System.String, System.Text.Encoding, Boolean, Int32)
   at System.IO.StreamReader..ctor(System.String, System.Text.Encoding)
   at System.IO.File.InternalReadAllLines(System.String, System.Text.Encoding)
   at System.IO.File.ReadAllLines(System.String)
   at XiboClient.XiboTraceListener.ProcessQueueToXmds()
   at System.Threading.ThreadHelper.ThreadStart_Context(System.Object)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)
   at System.Threading.ThreadHelper.ThreadStart()

**Comment by xibo-de** [comment]
just now

Ereignistyp:	Fehler
Ereignisquelle:	.NET Runtime 4.0 Error Reporting
Ereigniskategorie:	Keine
Ereigniskennung:	5000
Datum:		26.02.2015
Zeit:		10:30:31
Benutzer:		Nicht zutreffend
Computer:	HP43221471225
Beschreibung:
EventType clr20r3, P1 xiboclient.exe, P2 2.0.0.0, P3 54c69567, P4 mscorlib, P5 4.0.0.0, P6 52ccf750, P7 3fde, P8 1f4, P9 system.io.ioexception, P10 NIL.

Weitere Informationen über die Hilfe- und Supportdienste erhalten Sie unter http://go.microsoft.com/fwlink/events.asp.
Daten:
0000: 63 00 6c 00 72 00 32 00   c.l.r.2.
0008: 30 00 72 00 33 00 2c 00   0.r.3.,.
0010: 20 00 78 00 69 00 62 00    .x.i.b.
0018: 6f 00 63 00 6c 00 69 00   o.c.l.i.
0020: 65 00 6e 00 74 00 2e 00   e.n.t...
0028: 65 00 78 00 65 00 2c 00   e.x.e.,.
0030: 20 00 32 00 2e 00 30 00    .2...0.
0038: 2e 00 30 00 2e 00 30 00   ..0...0.
0040: 2c 00 20 00 35 00 34 00   ,. .5.4.
0048: 63 00 36 00 39 00 35 00   c.6.9.5.



Ereignistyp:	Fehler
Ereignisquelle:	.NET Runtime
Ereigniskategorie:	Keine
Ereigniskennung:	1026
Datum:		26.02.2015
Zeit:		10:30:48
Benutzer:		Nicht zutreffend
Computer:	HP43221471225
Beschreibung:
Application: XiboClient.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.IO.IOException
Stack:
   at System.IO.__Error.WinIOError(Int32, System.String)
   at System.IO.FileStream.Init(System.String, System.IO.FileMode, System.IO.FileAccess, Int32, Boolean, System.IO.FileShare, Int32, System.IO.FileOptions, SECURITY_ATTRIBUTES, System.String, Boolean, Boolean)
   at System.IO.FileStream..ctor(System.String, System.IO.FileMode, System.IO.FileAccess, System.IO.FileShare, Int32, System.IO.FileOptions)
   at System.IO.StreamReader..ctor(System.String, System.Text.Encoding, Boolean, Int32)
   at System.IO.StreamReader..ctor(System.String, System.Text.Encoding)
   at System.IO.File.InternalReadAllLines(System.String, System.Text.Encoding)
   at System.IO.File.ReadAllLines(System.String)
   at XiboClient.XiboTraceListener.ProcessQueueToXmds()
   at System.Threading.ThreadHelper.ThreadStart_Context(System.Object)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)
   at System.Threading.ThreadHelper.ThreadStart()

**Comment by dasgarner** [comment]
I don't see how that can be happening with this file [XiboClient.exe](https://github.com/dasgarner/xibo-dotnetclient/blob/develop/bin/x86/Release/XiboClient.exe?raw=true)

Are you sure you are using that?

**Comment by xibo-de** [comment]
my mistake
I had an old version.
they have now replaced

I test more ...

**Comment by jetski28** [comment]
Is that a new release or the same as before?

**Comment by ygurdag** [comment]
I downloaded the new exe but still error. This problem occurs while client sending lots of log and stat data   to server.(if there are lots of log_xx and stat_xx files on your xibo client library)  No internet, no problem.

**Comment by dasgarner** [comment]
I've added throttling to where it sends those, see attached commit for testing EXE.

**Comment by dasgarner** [comment]
I am closing this issue because we have moved all discussion and support to [community.xibo.org.uk](http://community.xibo.org.uk) and would like to tidy up GitHub so we can use this as a **bug tracker** only. If you are still having a problem, please repost on the [community site](http://community.xibo.org.uk) and please update your bookmarks for future questions!
