### ISSUE TITLE
Twitter module - marquee effects don't work

### ISSUE THREAD

**Issue by PeterMis** [xibosignage/xibo#558]
Other effects work just fine, but when you set effect to marquee (doesn't matter which one) it does nothing - it's the same as if it would be set to 'none'. This occur on both preview and the players.
This is only regarding twitter module, marquee effect works fine on text module.

Topic on community site:
https://community.xibo.org.uk/t/twitter-module-effects-not-working-on-windows/3001

**Comment by PeterMis** [comment]
1.7.5 still marquee = none, output wise // not sure if we changed it in 1.7.5 at the moment
1.8 - nearly there, only tweet text seems to be fine, with profile image, all returned images are shown at the beginning not before each tweet

**Comment by dasgarner** [comment]
Fixed the marquee bit in 1.7 - so that it now has the same issue as 1.8 (profile images stacked up).

That is due to this:

```css
p.profileimage img {width: 150px;float: left;padding-right: 20px;}
```

Change the template to this:
```css
p.profileimage img {width: 150px;padding-right: 20px;}
```

And its fine. I've submitted a backlog issue to look at this: #608

**Comment by slifty** [comment]
This still doesn't work on for me (using the latest builds from xibo.org.uk

The marquee plugin is never actually loaded -- the request for it is there, but jquery.marquee.js isn't in the local cache; I naively tried adding `$media->addModuleFile('modules/preview/vendor/jquery.marquee.min.js');` to the InstallFiles() method in twitter.module.php which didn't resolve the problem.

Manually adding jquery.marquee.js to my local xibo library / cache caused movement, but not a valid marquee.

Thoughts?

**Comment by dasgarner** [comment]
Please can you post on our community site describing your issue rather than commenting on an old bug. I suspect you need to run the module validation routine from the modules page. Thanks!
